### ISSUE TITLE
Release component source?

### ISSUE THREAD

**Issue by macMikey** [fourctv/FourDRESTApi#2]
Are you interested in releasing the source for the component? Since 4D has its own REST server now, but it consumes a client license for every connection (!), this project might become more interesting (and save me the time of writing my own 4D REST library...

**Comment by fourctv** [comment]
what do you mean? the source is here on github! the .4DB & .4DIndY are here, along with the built component!

**Comment by macMikey** [comment]
ah, thanks. when i was reading the install instructions, it was not clear that the source for the component was in the repo.
i was just starting to read through it when i posted that issue...
